### ISSUE TITLE
Following your guide breaks one's system

### ISSUE THREAD

**Issue by Silejonu** [CloudBytesDotDev/CloudBytes.dev#94]
Following [this guide](https://cloudbytes.dev/snippets/upgrade-python-to-latest-version-on-ubuntu-linux) results in X11 being uninstalled, among other important components.

**Comment by guazzabuglio** [comment]
Same thing happened to me. I haven't reinstalled Ubuntu yet. Holding out for a fix

**Comment by rehanhaider** [comment]
On further investigation, it seems this happens on specific systems using specific dependencies. However, the latest Python on Ubuntu now is v3.9, so this guide has been updated accordingly.

**Comment by Silejonu** [comment]
> On further investigation, it seems this happens on specific systems using specific dependencies. However, the latest Python on Ubuntu now is v3.9, so this guide has been updated accordingly.

My initial testing was on a fresh install of Ubuntu 20.04 in a VM and it resulted in an un-bootable system.
